title: Mahfujul Islam Mahee
logo: Assets/Image/headshot_circle.png
description: "Computer Science & Engineering | Machine Learning & Flutter Developer 📍 Sylhet, Bangladesh | ✉️ Email: mahee4090@gmail.com | 📱 Phone: +8801864827198"
show_downloads: false
theme: jekyll-theme-minimal
