title: Mahfujul Islam Mahee
logo: Assets/Image/headshot_circle.png
description:  "Computer Science & Engineering <br> Machine Learning & Flutter Developer <br><br> 📍 Sylhet, Bangladesh <br> ✉️ mahee4090@gmail.com <br> 📱 +8801864827198"
show_downloads: false
theme: jekyll-theme-minimal
